spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/didispace/config-repo-demo/
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 2005